name = "bitcoin-op"
compatibility_date = "2025-04-11"

[build]
command = "npm run build"
outdir = "public"  # Match your static assets directory

[pages]
assets = "public"  # Explicitly declare assets directory
not_found_handling = "single-page-application"  # Serve index.html for SPAs
run_worker_first = false  # Let assets serve directly without Worker intercept

[assets]
directory = "public"  # Alternative declaration for Workers
binding = "ASSETS"  # Optional binding name for Worker access
